"""EDGAR daily index files: what was filed on a day, by form type.

A daily index (`form.YYYYMMDD.idx`) is a plain-text report: a few header lines,
a column header, a dashed separator, then one row per filing. The parser here
is pure. Fetching and listing live in the same module in a later step; the DAG
stores the raw file before calling the parser.
"""

import re
from dataclasses import dataclass
from datetime import date
from enum import StrEnum


class Form13F(StrEnum):
    """The four 13F submission types. A StrEnum compares equal to its string."""

    HR = "13F-HR"
    HR_A = "13F-HR/A"
    NT = "13F-NT"
    NT_A = "13F-NT/A"

    @property
    def is_amendment(self) -> bool:
        return self.endswith("/A")


FORM_TYPES_13F = frozenset(Form13F)

# One row: form type, company name, CIK, filing date, file name. Anchored on the
# right because company names may contain runs of spaces and long form types shift
# the columns, so fixed offsets are not safe.
_ROW = re.compile(
    r"^(?P<form_type>\S+)\s+(?P<company>.*?)\s+(?P<cik>\d+)\s+(?P<filed>\d{8})\s+"
    r"(?P<path>edgar/\S+)\s*$"
)
_ACCESSION = re.compile(r"^\d{10}-\d{2}-\d{6}$")


class IndexParseError(ValueError):
    """A daily index row or header did not have the expected shape."""


@dataclass(frozen=True)
class IndexEntry:
    """One filing as the daily index reports it."""

    form_type: str
    company_name: str
    cik: int
    filed: date
    accession: str
    path: str

    @property
    def filing_folder(self) -> str:
        """Path of the filing's document folder on sec.gov, no dashes in the accession."""
        return f"/Archives/edgar/data/{self.cik}/{self.accession.replace('-', '')}/"


def parse_form_index(
    data: bytes | str,
    form_types: frozenset[str] | None = FORM_TYPES_13F,
) -> list[IndexEntry]:
    """Parse a `form.YYYYMMDD.idx` file into entries, keeping only `form_types`.

    Pass `form_types=None` to keep every row. Raises IndexParseError, with the
    1-based line number, on a row that does not match: the file is generated by
    the SEC, so an unreadable row is a format change worth stopping on.
    """
    # EDGAR index files predate UTF-8 on the site; latin-1 decodes every byte.
    text = data.decode("latin-1") if isinstance(data, bytes) else data
    lines = text.splitlines()
    first_row = _first_row_index(lines)

    entries: list[IndexEntry] = []
    for offset, line in enumerate(lines[first_row:], start=first_row + 1):
        if not line.strip():
            continue
        fields = _ROW.match(line)
        if fields is None:
            raise IndexParseError(f"line {offset} does not look like an index row: {line!r}")
        form_type = fields["form_type"]
        if form_types is not None and form_type not in form_types:
            continue
        entries.append(
            IndexEntry(
                form_type=form_type,
                company_name=fields["company"].strip(),
                cik=int(fields["cik"]),
                filed=_parse_filed(fields["filed"], offset),
                accession=_accession_from_path(fields["path"], offset),
                path=fields["path"],
            )
        )
    return entries


def _first_row_index(lines: list[str]) -> int:
    for i, line in enumerate(lines):
        if line.startswith("----"):
            return i + 1
    raise IndexParseError("no dashed separator line; not a daily index file")


def _parse_filed(yyyymmdd: str, line_no: int) -> date:
    try:
        return date.fromisoformat(yyyymmdd)
    except ValueError as exc:
        raise IndexParseError(f"line {line_no}: bad filing date {yyyymmdd!r}") from exc


def _accession_from_path(path: str, line_no: int) -> str:
    stem = path.rsplit("/", 1)[-1].removesuffix(".txt")
    if not _ACCESSION.match(stem):
        raise IndexParseError(f"line {line_no}: file name {path!r} carries no accession number")
    return stem
